name = "nostalgiamap"
compatibility_date = "2024-01-01"

type = "javascript"

# Define the build process
[build]
command = "npm run build"
directory = "workers-site"

# Bind the KV namespace
[[kv_namespaces]]
binding = "MY_KV"
id = "ab62445402804518b8670f0b73ced1a6"

# Specify the entry point for the Worker
main = "functions/kv.ts"

# Site configuration
[site]
bucket = ".next/static"
entry-point = "workers-site"

# Add this for Pages deployment
pages_build_output_dir = ".vercel/output/static"