name = "nostalgiamap"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = ".next/static"

[env.production]
pages_build_output_dir = ".vercel/output/static"
